// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2EzVyqHaqiWR8-4jR6nNXkqvYpi5HrnM',
    appId: '1:454731726278:web:c922c6d3ef74fa0229c6c7',
    messagingSenderId: '454731726278',
    projectId: 'gradproject2-60c76',
    authDomain: 'gradproject2-60c76.firebaseapp.com',
    storageBucket: 'gradproject2-60c76.appspot.com',
    measurementId: 'G-WPHRE4BN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9KqGK8tHomFliyl2DKgAHswVRY4Cb-HE',
    appId: '1:454731726278:android:5d7fd9e44d0397f329c6c7',
    messagingSenderId: '454731726278',
    projectId: 'gradproject2-60c76',
    storageBucket: 'gradproject2-60c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXHB_iVWOSClszFbHQ5uE_X80YzID7SQ',
    appId: '1:454731726278:ios:9bd5c4248a9fe58429c6c7',
    messagingSenderId: '454731726278',
    projectId: 'gradproject2-60c76',
    storageBucket: 'gradproject2-60c76.appspot.com',
    iosBundleId: 'com.example.gradproj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXHB_iVWOSClszFbHQ5uE_X80YzID7SQ',
    appId: '1:454731726278:ios:084b28d4f73e565529c6c7',
    messagingSenderId: '454731726278',
    projectId: 'gradproject2-60c76',
    storageBucket: 'gradproject2-60c76.appspot.com',
    iosBundleId: 'com.example.gradproj2.RunnerTests',
  );
}
